### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by corbanb** [rmagick-temp/rmagick#102]
Running into an issue getting rmagick to load. Environment below:

Image Magick

```
Version: ImageMagick 6.8.8-9 Q16 x86_64 2014-03-23 
Features: DPC Modules
Delegates: bzlib freetype jng jpeg ltdl png xml zlib
```

Rails 3.2.17
RMagick 2.13.2
OSX 10.9.2

When I run `rails server` it fails with the output of:

```
~/.rvm/gems/ruby-1.9.3-p545@myapp/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require': dlopen(~/.rvm/gems/ruby-1.9.3-p545@myapp/extensions/x86_64-darwin-13/1.9.1/rmagick-2.13.2/RMagick2.bundle, 9): Library not loaded: /usr/local/lib/libMagickCore-6.Q16.1.dylib (LoadError)
  Referenced from: ~/.rvm/gems/ruby-1.9.3-p545@myapp/extensions/x86_64-darwin-13/1.9.1/rmagick-2.13.2/RMagick2.bundle
  Reason: image not found - ~/.rvm/gems/ruby-1.9.3-p545@myapp/extensions/x86_64-darwin-13/1.9.1/rmagick-2.13.2/RMagick2.bundle
  from ~/.rvm/gems/ruby-1.9.3-p545@myapp/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
  from ~/.rvm/gems/ruby-1.9.3-p545@myapp/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
  from ~/.rvm/gems/ruby-1.9.3-p545@myapp/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
  from ~/.rvm/gems/ruby-1.9.3-p545@myapp/gems/rmagick-2.13.2/lib/rmagick.rb:11:in `<top (required)>'
  from ~/.rvm/gems/ruby-1.9.3-p545@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:76:in `require'
  from ~/.rvm/gems/ruby-1.9.3-p545@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  from ~/.rvm/gems/ruby-1.9.3-p545@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:72:in `each'
  from ~/.rvm/gems/ruby-1.9.3-p545@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:72:in `block in require'
  from ~/.rvm/gems/ruby-1.9.3-p545@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `each'
  from ~/.rvm/gems/ruby-1.9.3-p545@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `require'
  from ~/.rvm/gems/ruby-1.9.3-p545@global/gems/bundler-1.5.3/lib/bundler.rb:131:in `require'
  from ~/Sites/myapp/config/application.rb:7:in `<top (required)>'
  from ~/.rvm/gems/ruby-1.9.3-p545@myapp/gems/railties-3.2.17/lib/rails/commands.rb:53:in `require'
  from ~/.rvm/gems/ruby-1.9.3-p545@myapp/gems/railties-3.2.17/lib/rails/commands.rb:53:in `block in <top (required)>'
  from ~/.rvm/gems/ruby-1.9.3-p545@myapp/gems/railties-3.2.17/lib/rails/commands.rb:50:in `tap'
  from ~/.rvm/gems/ruby-1.9.3-p545@myapp/gems/railties-3.2.17/lib/rails/commands.rb:50:in `<top (required)>'
  from script/rails:6:in `require'
  from script/rails:6:in `<main>'
```

Any thoughts?

Edited: I do notice in the output above its looking for  `libMagickCore-6.Q16.1.dylib` but my system only has `/usr/local/lib/libMagickCore-6.Q16.2.dylib`. Not sure why it is picking up the wrong lib.

**Comment by corbanb** [comment]
SOLVED:
What I believe the issue was caused by was installing a newer version of ImageMagick when I did a `brew upgrade`. 

By doing `gem uninstall rmagick && gem install rmagick` I was able to get rmagick to find the new version. 

Hopefully this issues helps a few others.

**Comment by chamnap** [comment]
After I run `gem uninstall rmagick && gem install rmagick`, I got the following:

``` ruby
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.1@yoolk_core/gems/rmagick-2.13.2/lib/rmagick.rb:44: warning: already initialized constant Magick::PercentGeometry
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.1@yoolk_core/gems/rmagick-2.13.2/lib/RMagick.rb:44: warning: previous definition of PercentGeometry was here
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.1@yoolk_core/gems/rmagick-2.13.2/lib/rmagick.rb:45: warning: already initialized constant Magick::AspectGeometry
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.1@yoolk_core/gems/rmagick-2.13.2/lib/RMagick.rb:45: warning: previous definition of AspectGeometry was here
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.1@yoolk_core/gems/rmagick-2.13.2/lib/rmagick.rb:46: warning: already initialized constant Magick::LessGeometry
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.1@yoolk_core/gems/rmagick-2.13.2/lib/RMagick.rb:46: warning: previous definition of LessGeometry was here
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.1@yoolk_core/gems/rmagick-2.13.2/lib/rmagick.rb:47: warning: already initialized constant Magick::GreaterGeometry
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.1@yoolk_core/gems/rmagick-2.13.2/lib/RMagick.rb:47: warning: previous definition of GreaterGeometry was here
....
...
```

@corbanb, you have any idea to fix this?

**Comment by BerkeleyTrue** [comment]
I am having the same issue. I have the latest version of RMagick installed.

```
/Library/Ruby/Gems/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require': dlopen(/Library/Ruby/Gems/2.0.0/gems/rmagick-2.13.3/lib/RMagick2.bundle, 9): Library not loaded: /usr/local/lib/libltdl.7.dylib (LoadError)
  Referenced from: /usr/local/opt/imagemagick/lib/libMagickCore-6.Q16.2.dylib
  Reason: image not found - /Library/Ruby/Gems/2.0.0/gems/rmagick-2.13.3/lib/RMagick2.bundle
        from /Library/Ruby/Gems/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
        from /Library/Ruby/Gems/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Library/Ruby/Gems/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/rmagick-2.13.3/lib/rmagick.rb:11:in `<top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.6.4/lib/bundler/runtime.rb:76:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.6.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.6.4/lib/bundler/runtime.rb:72:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.6.4/lib/bundler/runtime.rb:72:in `block in require'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.6.4/lib/bundler/runtime.rb:61:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.6.4/lib/bundler/runtime.rb:61:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.6.4/lib/bundler.rb:132:in `require'
        from /Users/berkeley/ruby/justhearit-html5/config/application.rb:7:in `<top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/railties-3.2.12/lib/rails/commands.rb:53:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/railties-3.2.12/lib/rails/commands.rb:53:in `block in <top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/railties-3.2.12/lib/rails/commands.rb:50:in `tap'
        from /Library/Ruby/Gems/2.0.0/gems/railties-3.2.12/lib/rails/commands.rb:50:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

OSX 10.9.4
Rails 3.2.12
RMagick 2.13.3
imagemagick 6.8.9-7

**Comment by vipyne** [comment]
@BerkeleyTrue try updating to imagemagick 6.8.9-8 and uninstall and reinstall rmagick gem.

**Comment by BerkeleyTrue** [comment]
I don't remember exactly how I got around this issue. Still have the same versions of imagemagick and RMagick installed. Rails is now version 4.1.5. Sorry about not posting my solution here :(

**Comment by OpakAlex** [comment]
+1 only for ubuntu

**Comment by nichthinkof30** [comment]
Try delete your rails app gemfile.lock and reinstall again, your previous gemfile might stuck with the previous version
