### ISSUE TITLE
Segfaults w/ 1.9.2 and threads

### ISSUE THREAD

**Issue by vangberg** [rmagick-temp/rmagick#16]
Using RMagick in a thread under 1.9.2 causes a segfault.

```
$ cat thread-rmagick.rb
require "RMagick"

Thread.new {
  i = Magick::Image.read("image.png")
}

$ ruby thread-rmagick.rb
thread-rmagick.rb:4: [BUG] Segmentation fault
ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-darwin10.4.0]

-- control frame ----------
c:0004 p:---- s:0011 b:0011 l:000010 d:000010 CFUNC  :read
c:0003 p:0019 s:0007 b:0007 l:001598 d:000006 BLOCK  thread-rmagick.rb:4
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:---- s:0002 b:0002 l:000001 d:000001 TOP   
---------------------------
-- Ruby level backtrace information ----------------------------------------
thread-rmagick.rb:4:in `block in <main>'
thread-rmagick.rb:4:in `read'

-- C level backtrace information -------------------------------------------

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html
```

Ruby: 1.9.2p0
RMagick: 2.13.1
ImageMagick: 6.6.4-2

Mac OS X 10.6

**Comment by biilmann** [comment]
Same error here
Ruby 1.9.2p0
RMagick: 2.13.1
ImageMagick: 6.6.2-0

http://gist.github.com/587437

**Comment by cashby** [comment]
Same error here
Ruby 1.9.2p0
RMagick 2.13.1
Dragonfly 0.7.4

git://gist.github.com/595334.git

**Comment by cashby** [comment]
Here is my Rails 3 server log from the terminal. Everything works fine until I hit a page that has links to images that were created with Dragonfly and RMagick.

git://gist.github.com/595398.git

**Comment by luma** [comment]
It may be this issue: http://article.gmane.org/gmane.comp.lib.qt.general/26147

If it is, and it was for me, a temporally work around is too install Image Magick with openmp disabled.

  brew install -f imagemagick --disable-openmp

**Comment by paddyinpdx** [comment]
@luma: Great tip! Just worked for me, a total RMagick noob.

**Comment by bjensen** [comment]
Disabling openmp did the trick for me as well. Thank you!

Rails 3.0.4, Ruby 1.9.2, ImageMagick 6.6.7-1 installed through homebrew

**Comment by luma** [comment]
@paddyinpdx @pointman De nada,  glad it helped :-)

**Comment by linduxed** [comment]
Candidate for closing, @mmaiza.
