### ISSUE TITLE
Cannot compile on Slackware 13.1; complains of 'partial' ImageMagick

### ISSUE THREAD

**Issue by anoother** [rmagick-temp/rmagick#21]
Neither the gem, nor tarballs of 2.13.1 or 2.13.0 will compile:

```
 $ ruby setup.rb
  ---> lib
  ---> lib/rvg
  <--- lib/rvg
  <--- lib
  ---> ext
  ---> ext/RMagick
  /usr/bin/ruby /home/ahmad/setup/software/ebookproduction/rmagick/ RMagick-2.13.1/ext/RMagick/extconf.rb
  checking for Ruby version >= 1.8.5... *** /home/ahmad/setup/software/ebookproduction/rmagick/RMagick-2.13.1/ext/RMagick/extconf.rb failed ***
  Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.

  Provided configuration options:
      --with-opt-dir
      --without-opt-dir
      --with-opt-include
      --without-opt-include=${opt-dir}/include
      --with-opt-lib
      --without-opt-lib=${opt-dir}/lib
      --with-make-prog
      --without-make-prog
      --srcdir=/home/ahmad/setup/software/ebookproduction/rmagick/RMagick-2.13.1/ext/RMagick
      --curdir
      --ruby=/usr/bin/ruby
  /usr/lib/ruby/1.9.1/mkmf.rb:242:in `initialize': Permission denied - mkmf.log (Errno::EACCES)
      from /usr/lib/ruby/1.9.1/mkmf.rb:242:in `open'
      from /usr/lib/ruby/1.9.1/mkmf.rb:242:in `log_open'
      from /usr/lib/ruby/1.9.1/mkmf.rb:247:in `open'
      from /usr/lib/ruby/1.9.1/mkmf.rb:272:in `postpone'
      from /usr/lib/ruby/1.9.1/mkmf.rb:669:in `checking_for'
      from /home/ahmad/setup/software/ebookproduction/rmagick/RMagick-2.13.1/ext/RMagick/extconf.rb:114:in `<main>'
  setup.rb:655:in `command': system("/usr/bin/ruby" "/home/ahmad/setup/software/ebookproduction/rmagick/RMagick-2.13.1/ext/RMagick/extconf.rb") failed (RuntimeError)
      from setup.rb:660:in `ruby'
      from setup.rb:1238:in `extconf'
      from setup.rb:1230:in `config_dir_ext'
      from setup.rb:1532:in `block in traverse'
      from setup.rb:1549:in `dive_into'
      from setup.rb:1530:in `traverse'
      from setup.rb:1534:in `block (2 levels) in traverse'
      from setup.rb:1533:in `each'
      from setup.rb:1533:in `block in traverse'
      from setup.rb:1549:in `dive_into'
      from setup.rb:1530:in `traverse'
      from setup.rb:1524:in `block in exec_task_traverse'
      from setup.rb:1519:in `each'
      from setup.rb:1519:in `exec_task_traverse'
      from setup.rb:1223:in `exec_config'
      from setup.rb:991:in `exec_config'
      from setup.rb:812:in `invoke'
      from setup.rb:772:in `invoke'
      from setup.rb:1578:in `<main>'
```

Slackware 13.1 uses Ruby 1.9.1 and ImageMagick 6.5.9

Please help!

**Comment by linduxed** [comment]
Is this still an issue? Have you tried with newer versions of Ruby and RMagick?

I can't reproduce this on Arch. @mmaiza

**Comment by vassilevsky** [comment]
It looks like just a permission problem.

https://github.com/gemhome/rmagick/issues/12#issuecomment-76605318
