### ISSUE TITLE
rmagick 1.15.17 Failed Install on Mac OS X

### ISSUE THREAD

**Issue by ylluminate** [rmagick-temp/rmagick#31]
Attempting to `bundle install` a Gemfile from ChiliProject and running into an issue with rmagick compilation:

Gemfile: https://gist.github.com/1112118

The error in question appears to be:
rmagick.h:20:20: error: intern.h: No such file or directory

But the chunk that contains this in context is:

<pre>
---> ext/RMagick
make
gcc -I. -I/Users/username/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/x86_64-darwin11.0.0 -I/Users/username/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/Users/username/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I/Volumes/StorageVolume/Users/username/.rvm/gems/ruby-1.9.2-p290/gems/rmagick-1.15.17/ext/RMagick -DRUBY_VERSION=0x192  -I/usr/local/include/ImageMagick -fno-common   -o rmdraw.o -c rmdraw.c
In file included from rmdraw.c:10:
rmagick.h:20:20: error: intern.h: No such file or directory
In file included from rmagick.h:21,
                 from rmdraw.c:10:
/Users/username/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h"
rmdraw.c: In function ‘Draw_annotate’:
rmdraw.c:448: warning: ‘InterpretImageAttributes’ is deprecated (declared at /usr/local/include/ImageMagick/magick/deprecate.h:96)
rmdraw.c: In function ‘get_dummy_tm_img’:
rmdraw.c:1419: warning: ‘AllocateImage’ is deprecated (declared at /usr/local/include/ImageMagick/magick/deprecate.h:119)
rmdraw.c:1427: error: too many arguments to function ‘rb_cvar_set’
rmdraw.c: In function ‘get_type_metrics’:
rmdraw.c:1504: warning: ‘InterpretImageAttributes’ is deprecated (declared at /usr/local/include/ImageMagick/magick/deprecate.h:96)
make[1]: *** [rmdraw.o] Error 1
setup.rb:655:in `command': system("make") failed (RuntimeError)
    from setup.rb:664:in `make'
    from setup.rb:1258:in `setup_dir_ext'
    from setup.rb:1532:in `block in traverse'
    from setup.rb:1549:in `dive_into'
    from setup.rb:1530:in `traverse'
    from setup.rb:1534:in `block (2 levels) in traverse'
    from setup.rb:1533:in `each'
    from setup.rb:1533:in `block in traverse'
    from setup.rb:1549:in `dive_into'
    from setup.rb:1530:in `traverse'
    from setup.rb:1524:in `block in exec_task_traverse'
    from setup.rb:1519:in `each'
    from setup.rb:1519:in `exec_task_traverse'
    from setup.rb:1246:in `exec_setup'
    from setup.rb:996:in `exec_setup'
    from setup.rb:826:in `invoke'
    from setup.rb:772:in `invoke'
    from setup.rb:1578:in `<main>'
make: *** [all] Error 1

</pre>

Any help would be much appreciated so as to get this resolved.

**Comment by mmaiza** [comment]
This means that rmagick is unable to find some of the header file. It could be because your path is not set correctly or because your imagemagick installation failed. Please follow the following instruction http://rmagick.rubyforge.org/install-osx.html and make sure you see no errors when installing imagemagick. You should then be able to do the bundle install.

Best Regards,
Moncef Maiza

-----Original Message-----
From: ylluminate [mailto:reply@reply.github.com] 
Sent: Thursday, July 28, 2011 2:02 PM
To: moncef@datasieve.com
Subject: [rmagick] rmagick 1.15.17 Failed Install on Mac OS X (#31)

Attempting to `bundle install` a Gemfile from ChiliProject and running into an issue with rmagick compilation:

Gemfile: https://gist.github.com/1112118

The error in question appears to be:
rmagick.h:20:20: error: intern.h: No such file or directory

But the chunk that contains this in context is:

<pre>
---> ext/RMagick
make
gcc -I. -I/Users/username/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/x86_64-darwin11.0.0 -I/Users/username/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/Users/username/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I/Volumes/StorageVolume/Users/username/.rvm/gems/ruby-1.9.2-p290/gems/rmagick-1.15.17/ext/RMagick -DRUBY_VERSION=0x192  -I/usr/local/include/ImageMagick -fno-common   -o rmdraw.o -c rmdraw.c
In file included from rmdraw.c:10:
rmagick.h:20:20: error: intern.h: No such file or directory
In file included from rmagick.h:21,
                 from rmdraw.c:10:
/Users/username/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h"
rmdraw.c: In function ‘Draw_annotate’:
rmdraw.c:448: warning: ‘InterpretImageAttributes’ is deprecated (declared at /usr/local/include/ImageMagick/magick/deprecate.h:96)
rmdraw.c: In function ‘get_dummy_tm_img’:
rmdraw.c:1419: warning: ‘AllocateImage’ is deprecated (declared at /usr/local/include/ImageMagick/magick/deprecate.h:119)
rmdraw.c:1427: error: too many arguments to function ‘rb_cvar_set’
rmdraw.c: In function ‘get_type_metrics’:
rmdraw.c:1504: warning: ‘InterpretImageAttributes’ is deprecated (declared at /usr/local/include/ImageMagick/magick/deprecate.h:96)
make[1]: *** [rmdraw.o] Error 1
setup.rb:655:in `command': system("make") failed (RuntimeError)
    from setup.rb:664:in `make'
    from setup.rb:1258:in `setup_dir_ext'
    from setup.rb:1532:in `block in traverse'
    from setup.rb:1549:in `dive_into'
    from setup.rb:1530:in `traverse'
    from setup.rb:1534:in `block (2 levels) in traverse'
    from setup.rb:1533:in `each'
    from setup.rb:1533:in `block in traverse'
    from setup.rb:1549:in `dive_into'
    from setup.rb:1530:in `traverse'
    from setup.rb:1524:in `block in exec_task_traverse'
    from setup.rb:1519:in `each'
    from setup.rb:1519:in `exec_task_traverse'
    from setup.rb:1246:in `exec_setup'
    from setup.rb:996:in `exec_setup'
    from setup.rb:826:in `invoke'
    from setup.rb:772:in `invoke'
    from setup.rb:1578:in `<main>'
make: *** [all] Error 1

</pre>


Any help would be much appreciated so as to get this resolved.

## 

Reply to this email directly or view it on GitHub:
https://github.com/rmagick/rmagick/issues/31

**Comment by ylluminate** [comment]
Thanks for the note.  Unfortunately ImageMagick installs just fine and is installed fine:

<pre>
$mogrify --version
Version: ImageMagick 6.7.1-0 2011-07-28 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP   
</pre>


I was able to run the following seemingly just fine:

<pre>
./configure --prefix=/usr/local --disable-static --without-fontconfig --with-modules --without-perl --without-magick-plus-plus --with-quantum-depth=8 --with-gs-font-dir=/usr/local/share/ghostscript/fonts --disable-openmp && make && sudo make install
</pre>


Following this I attempted to go back to the `bundle install` and come up with the above issue.

It appears to be missing intern.h which seems to be part of Ruby source.  This does also appear to be available as it is present here: /Users/username/.rvm/src/ruby-1.9.2-p290/include/ruby/intern.h

Thanks,

-George

**Comment by mmaiza** [comment]
Looking at the gcc command that fails I do not see a path that leads to intern.h. Check your path and see what comes first. You may have had an old install of Ruby and it is still searching there. In this case you would have to modify the path. Something is wrong with your configuration and you will have to look for it.
From a console do: which ruby to find out where it is looking? If the root of the path is not the same as the one where inten.h lied then you need to fix your PATH variable.

Moncef

-----Original Message-----

**Comment by ylluminate** [comment]
I actually switched to ruby ruby-1.8.7-p352 from ruby-1.9.2-p290 and this seemed to help. Still having some odd crashes with ruby itself, but that appears to perhaps be from some gcc issue on Lion which tries to use LLVM.  I did force it over to gcc, but still some odd sporadic crashes.

**Comment by ycherniavskyi** [comment]
I have the same problem. After some investigate I have understood that proble not in any environment configuration, it is in rmagick library version.
From http://rmagick.rubyforge.org
_RMagick 1 does not support any features added to ImageMagick 6.3.0 and later and does not work with Ruby 1.9._
and we try to compile RMagick 1.15.17 under Ruby 1.9.2 :).
