### ISSUE TITLE
ERROR:  Error installing rmagick - Failed to build gem native extension.

### ISSUE THREAD

**Issue by jamonholmgren** [rmagick-temp/rmagick#95]
This seems to be a long shot, since issues seem to be ignored here, but I'm really stumped.

I'm getting the following:

```
$ gem install rmagick -v '2.13.2'
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
    ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby extconf.rb
checking for Ruby version >= 1.8.5... yes
checking for gcc-4.2... yes
checking for Magick-config... yes

Warning: Found a partial ImageMagick installation. Your operating system likely has some built-in ImageMagick libraries but not all of ImageMagick. This will most likely cause problems at both compile and runtime.
Found partial installation at: /usr/local
checking for ImageMagick version >= 6.4.9... yes
checking for HDRI disabled version of ImageMagick... yes
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/bin/ruby
/usr/local/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:587:in `try_cpp'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:1067:in `block in have_header'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:1066:in `have_header'
    from extconf.rb:194:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/jh/.gem/ruby/2.1.0/gems/rmagick-2.13.2 for inspection.
Results logged to /Users/jh/.gem/ruby/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/rmagick-2.13.2/gem_make.out
```

As you can see, I have the proper version of gcc (4.2) linked. I did `brew install imagemagick` and it seemed to install fine. However, it continues to give me this error.

**Comment by jamonholmgren** [comment]
My mkmf.log:

```
    checking for Ruby version >= 1.8.5... -------------------- yes

    --------------------

    find_executable: checking for gcc-4.2... -------------------- yes

    --------------------

    find_executable: checking for Magick-config... -------------------- yes

    --------------------


    Warning: Found a partial ImageMagick installation. Your operating system likely has some built-in ImageMagick libraries but not all of ImageMagick. This will most likely cause problems at both compile and runtime.
    Found partial installation at: /usr/local
    checking for ImageMagick version >= 6.4.9... -------------------- yes

    --------------------

    checking for HDRI disabled version of ImageMagick... -------------------- yes

    --------------------

    "gcc-4.2 -o conftest -I/usr/local/include/ruby-2.1.0/x86_64-darwin13.0 -I/usr/local/include/ruby-2.1.0/ruby/backward -I/usr/local/include/ruby-2.1.0 -I.  -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/6.8.7-7/include/ImageMagick-6   -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/6.8.7-7/include/ImageMagick-6  conftest.c  -L. -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/gdbm/lib -L/usr/local/opt/libffi/lib  -L/usr/local/Cellar/imagemagick/6.8.7-7/lib -lMagickCore-6.Q16     -L/usr/local/Cellar/imagemagick/6.8.7-7/lib -lMagickCore-6.Q16   -lruby-static -framework CoreFoundation  -lpthread -lgmp -ldl -lobjc "
    sh: line 1: 50559 Trace/BPT trap: 5       /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk / -find as 2> /dev/null
    as: error: unable to find utility "as", not a developer tool or in PATH
    checked program was:
    /* begin */
    1: #include "ruby.h"
    2: 
    3: int main(int argc, char **argv)
    4: {
    5:   return 0;
    6: }
    /* end */
```

**Comment by dmarkow** [comment]
Running `xcodebuild -sdk / -find as` should output something like this:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/as
```

What happens when you run it? The mkmf.log output suggests that you may be missing it.

Also, what does `brew doctor` print? Have you tried reinstalling the latest command line tools and/or Xcode?

**Comment by jamonholmgren** [comment]
I've been working through this and tried that and it did show that path. I added that path to my `PATH` (which appears to have worked).

```
export PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:$PATH
```

But now I'm getting a different error in my mkmf.log:

```
"gcc-4.2 -o conftest -I/usr/local/include/ruby-2.1.0/x86_64-darwin13.0 -I/usr/local/include/ruby-2.1.0/ruby/backward -I/usr/local/include/ruby-2.1.0 -I.  -I/usr/local/Cellar/imagemagick/6.6.7-0/include/ImageMagick  -I/usr/local/Cellar/imagemagick/6.6.7-0/include/ImageMagick  conftest.c  -L. -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/gdbm/lib -L/usr/local/opt/libffi/lib  -L/usr/local/Cellar/imagemagick/6.6.7-0/lib     -L/usr/local/Cellar/imagemagick/6.6.7-0/lib -lMagickCore -lfreetype -ljpeg -llzma -lbz2 -lz -lm -lpthread -lltdl  -lruby-static -framework CoreFoundation  -lpthread -lgmp -ldl -lobjc "
ld: library not found for -lruby-static
collect2: ld returned 1 exit status
```

**Comment by jamonholmgren** [comment]
Brew is updated and ready to brew.

Current mkmf.log: https://gist.github.com/jamonholmgren/ff8cc58def2aa4bbbbe6
Current terminal output: https://gist.github.com/jamonholmgren/46b48fe86f03b90be61d

**Comment by jamonholmgren** [comment]
Reinstalled Xcode just last week.

**Comment by jamonholmgren** [comment]
I switched to `mini_magick` and it installed fine.

But...now I'm having the exact same problem with `mysql2`.

**Comment by jamonholmgren** [comment]
It appears that Ruby 2.1 may be part of the problem. If I switch back to Ruby 2.0, it works fine.

**Comment by jamonholmgren** [comment]
This fixed the mysql2 issue.

https://github.com/brianmario/mysql2/issues/481
